version: '3.1'

services:
  mongo:
    image: mongo:3.0.15
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  elasticsearch:
    image: elasticsearch:2.3
    ports:
      - 9200:9200
    volumes:
      - ./elastic_config:/usr/share/elasticsearch/config


  kibana:
    image: kibana:4.5
    ports:
      - 5601:5601
